server.port=8080

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

naver.search.client-id=${NAVER_SEARCH_CLIENT_ID:}
naver.search.client-secret=${NAVER_SEARCH_CLIENT_SECRET:}

youtube.api-key=${YOUTUBE_API_KEY:}
